<a href="https://colab.research.google.com/github/Prishletsova/Data_analytics_tools_for_solving_application_problems-/blob/main/%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D1%8F%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [56]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [57]:
a = np.zeros((1,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


3) Создать вектор заполненный 7-ами размера 7

In [58]:
b = np.full((1, 7), 7)
print(b)

[[7 7 7 7 7 7 7]]


4) Создать вектор заполненный четными числами от 10 до 100

In [59]:
c = np.arange(10, 100)
print(c[c % 2 == 0])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [60]:
d = np.random.randint(2,75,(5,5))
print("Изначальный массив:", d)
d1 = d[::-1]
print("")
print("Перевернутый массив:", d1)

Изначальный массив: [[27 28 44 12 39]
 [ 2 24 14 15 64]
 [38 49 44 66 61]
 [32 30 13 58 55]
 [ 6 44  3 12 11]]

Перевернутый массив: [[ 6 44  3 12 11]
 [32 30 13 58 55]
 [38 49 44 66 61]
 [ 2 24 14 15 64]
 [27 28 44 12 39]]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [61]:
e = np.arange(9)
e = e.reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [62]:
np.eye(4)
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [63]:
f = np.full((4, 4), 7)
np.fill_diagonal(f, np.arange(1, 5))
print(f)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [64]:
g = np.array([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], \
              [0, 1, 2, 3, 4]])
print(g)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [65]:
h = np.random.randint(1,100, (10, 10))
print('Matrix:\n', h)

for i in range(len(h)):
    matsum = sum(h[i])
    matmean = matsum / len(h[i])
    h[i] = [element - matmean for element in h[i]]
print('\nNewMatrix:\n', h)

Matrix:
 [[91 30 63 57 51 86 80  2 58 93]
 [45 27 41 46 69 61 30 79 52 33]
 [86 63 30 65 19 24 60 40 69 50]
 [53 49 79 45 56 82 67 50 20 66]
 [23  6 92 98 65 81 97 30 32 78]
 [82 83 59 35 49 35 87 55 30  4]
 [56 22 79  7 45 72 89 56 32 49]
 [15 18 25 80 61 95 32 27 23 40]
 [ 5 18 70 83 93  3 97 39 30 19]
 [ 4 77 62 24 62 87 89 35 38 80]]

NewMatrix:
 [[ 29 -31   1  -4 -10  24  18 -59  -3  31]
 [ -3 -21  -7  -2  20  12 -18  30   3 -15]
 [ 35  12 -20  14 -31 -26   9 -10  18   0]
 [ -3  -7  22 -11   0  25  10  -6 -36   9]
 [-37 -54  31  37   4  20  36 -30 -28  17]
 [ 30  31   7 -16  -2 -16  35   3 -21 -47]
 [  5 -28  28 -43  -5  21  38   5 -18  -1]
 [-26 -23 -16  38  19  53  -9 -14 -18  -1]
 [-40 -27  24  37  47 -42  51  -6 -15 -26]
 [-51  21   6 -31   6  31  33 -20 -17  24]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [66]:
i = np.random.randint(1, 100, (10, 10))
print("Matrix:\n", i)
column_means = np.mean(i, axis=0)
i = i - column_means
print("\nNewMatrix: \n", i)

Matrix:
 [[63 98 40 27 26 88 79 47 44 44]
 [73 74 81 22 93 68 95 60 80 85]
 [34 41 38 32 33 23 77 24 46 43]
 [30 76 35  6 36 91 77 23  8 64]
 [80 59 30 29 75 64  6 38 55 41]
 [96 75 36 46 36 72 31  4 41 70]
 [32 48 75 65 49 88 25 64 11 12]
 [45 67 75 26 53 37 63 28 92 29]
 [48 38 98 89  4 37 35  9 51 18]
 [53 14 39  1  4 58 57 98 84 85]]

NewMatrix: 
 [[  7.6  39.  -14.7  -7.3 -14.9  25.4  24.5   7.5  -7.2  -5.1]
 [ 17.6  15.   26.3 -12.3  52.1   5.4  40.5  20.5  28.8  35.9]
 [-21.4 -18.  -16.7  -2.3  -7.9 -39.6  22.5 -15.5  -5.2  -6.1]
 [-25.4  17.  -19.7 -28.3  -4.9  28.4  22.5 -16.5 -43.2  14.9]
 [ 24.6   0.  -24.7  -5.3  34.1   1.4 -48.5  -1.5   3.8  -8.1]
 [ 40.6  16.  -18.7  11.7  -4.9   9.4 -23.5 -35.5 -10.2  20.9]
 [-23.4 -11.   20.3  30.7   8.1  25.4 -29.5  24.5 -40.2 -37.1]
 [-10.4   8.   20.3  -8.3  12.1 -25.6   8.5 -11.5  40.8 -20.1]
 [ -7.4 -21.   43.3  54.7 -36.9 -25.6 -19.5 -30.5  -0.2 -31.1]
 [ -2.4 -45.  -15.7 -33.3 -36.9  -4.6   2.5  58.5  32.8  35.9]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [67]:
j = np.random.randint(1, 100, (5, 5))
print("Matrix:\n", j)

maxi = np.max(j, axis=1)
mini = np.min(j, axis=1)
new_matrix = np.column_stack((j, maxi, mini))
print("\nNewMatrix:\n", new_matrix)

Matrix:
 [[90 53 90  3 81]
 [36 85 89 74 97]
 [ 3 60 75 98 60]
 [ 7 73 98 48 16]
 [ 3 48  6 25 27]]

NewMatrix:
 [[90 53 90  3 81 90  3]
 [36 85 89 74 97 97 36]
 [ 3 60 75 98 60 98  3]
 [ 7 73 98 48 16 98  7]
 [ 3 48  6 25 27 48  3]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [68]:
k = np.array(range(1, 51))
print("Original vector:\n", k)

l = k[k % 2 == 1]
m = k[k % 2 == 0]

print("\nOdd vector:\n", l)
print("\nEven vector:\n", m)

l.resize(5, 5)
m.resize(5, 5)

print("\nOdd matrix:\n", l)
print("\nEven matrix:\n", m)

product = l*m
print("\nMatrix product:\n", product)

#try:
#    inverse = np.linalg.inv(product)
#except LinAlgError  as s:
#    print("Определитель равен нулю, поэтому вычислить обратную матрицу" \
#        "не получится")

# print("\nInverse matrix:\n", inverse)

Original vector:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Odd vector:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

Even vector:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]

Odd matrix:
 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

Even matrix:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

Matrix product:
 [[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [69]:
n = np.zeros((8,8))
n[1::2, ::2] = 1
n[0::2, 1::2] = 1
print(n)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
